// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: getTeacherInfo.proto

package getTeacherInfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Worknum string `protobuf:"bytes,3,opt,name=worknum,proto3" json:"worknum,omitempty"`
}

func (x *RequestInfo) Reset() {
	*x = RequestInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getTeacherInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInfo) ProtoMessage() {}

func (x *RequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_getTeacherInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInfo.ProtoReflect.Descriptor instead.
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return file_getTeacherInfo_proto_rawDescGZIP(), []int{0}
}

func (x *RequestInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestInfo) GetWorknum() string {
	if x != nil {
		return x.Worknum
	}
	return ""
}

type ResponseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teacherinfo []string `protobuf:"bytes,1,rep,name=teacherinfo,proto3" json:"teacherinfo,omitempty"`
}

func (x *ResponseInfo) Reset() {
	*x = ResponseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getTeacherInfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseInfo) ProtoMessage() {}

func (x *ResponseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_getTeacherInfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseInfo.ProtoReflect.Descriptor instead.
func (*ResponseInfo) Descriptor() ([]byte, []int) {
	return file_getTeacherInfo_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseInfo) GetTeacherinfo() []string {
	if x != nil {
		return x.Teacherinfo
	}
	return nil
}

var File_getTeacherInfo_proto protoreflect.FileDescriptor

var file_getTeacherInfo_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72,
	0x6b, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b,
	0x6e, 0x75, 0x6d, 0x22, 0x30, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65,
	0x72, 0x69, 0x6e, 0x66, 0x6f, 0x32, 0x3f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63,
	0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x65,
	0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0c, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x3b, 0x67, 0x65, 0x74,
	0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_getTeacherInfo_proto_rawDescOnce sync.Once
	file_getTeacherInfo_proto_rawDescData = file_getTeacherInfo_proto_rawDesc
)

func file_getTeacherInfo_proto_rawDescGZIP() []byte {
	file_getTeacherInfo_proto_rawDescOnce.Do(func() {
		file_getTeacherInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_getTeacherInfo_proto_rawDescData)
	})
	return file_getTeacherInfo_proto_rawDescData
}

var file_getTeacherInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getTeacherInfo_proto_goTypes = []any{
	(*RequestInfo)(nil),  // 0: RequestInfo
	(*ResponseInfo)(nil), // 1: ResponseInfo
}
var file_getTeacherInfo_proto_depIdxs = []int32{
	0, // 0: GetTeacherInfo.GetTeacherInfo:input_type -> RequestInfo
	1, // 1: GetTeacherInfo.GetTeacherInfo:output_type -> ResponseInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getTeacherInfo_proto_init() }
func file_getTeacherInfo_proto_init() {
	if File_getTeacherInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_getTeacherInfo_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RequestInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getTeacherInfo_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ResponseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getTeacherInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getTeacherInfo_proto_goTypes,
		DependencyIndexes: file_getTeacherInfo_proto_depIdxs,
		MessageInfos:      file_getTeacherInfo_proto_msgTypes,
	}.Build()
	File_getTeacherInfo_proto = out.File
	file_getTeacherInfo_proto_rawDesc = nil
	file_getTeacherInfo_proto_goTypes = nil
	file_getTeacherInfo_proto_depIdxs = nil
}
