// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: getTeacherInfo.proto

package getTeacherInfo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	GetTeacherInfo_GetTeacherInfo_FullMethodName = "/GetTeacherInfo/GetTeacherInfo"
)

// GetTeacherInfoClient is the client API for GetTeacherInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetTeacherInfoClient interface {
	GetTeacherInfo(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*ResponseInfo, error)
}

type getTeacherInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewGetTeacherInfoClient(cc grpc.ClientConnInterface) GetTeacherInfoClient {
	return &getTeacherInfoClient{cc}
}

func (c *getTeacherInfoClient) GetTeacherInfo(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*ResponseInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseInfo)
	err := c.cc.Invoke(ctx, GetTeacherInfo_GetTeacherInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetTeacherInfoServer is the server API for GetTeacherInfo service.
// All implementations must embed UnimplementedGetTeacherInfoServer
// for forward compatibility
type GetTeacherInfoServer interface {
	GetTeacherInfo(context.Context, *RequestInfo) (*ResponseInfo, error)
	mustEmbedUnimplementedGetTeacherInfoServer()
}

// UnimplementedGetTeacherInfoServer must be embedded to have forward compatible implementations.
type UnimplementedGetTeacherInfoServer struct {
}

func (UnimplementedGetTeacherInfoServer) GetTeacherInfo(context.Context, *RequestInfo) (*ResponseInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeacherInfo not implemented")
}
func (UnimplementedGetTeacherInfoServer) mustEmbedUnimplementedGetTeacherInfoServer() {}

// UnsafeGetTeacherInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetTeacherInfoServer will
// result in compilation errors.
type UnsafeGetTeacherInfoServer interface {
	mustEmbedUnimplementedGetTeacherInfoServer()
}

func RegisterGetTeacherInfoServer(s grpc.ServiceRegistrar, srv GetTeacherInfoServer) {
	s.RegisterService(&GetTeacherInfo_ServiceDesc, srv)
}

func _GetTeacherInfo_GetTeacherInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetTeacherInfoServer).GetTeacherInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetTeacherInfo_GetTeacherInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetTeacherInfoServer).GetTeacherInfo(ctx, req.(*RequestInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// GetTeacherInfo_ServiceDesc is the grpc.ServiceDesc for GetTeacherInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetTeacherInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GetTeacherInfo",
	HandlerType: (*GetTeacherInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTeacherInfo",
			Handler:    _GetTeacherInfo_GetTeacherInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "getTeacherInfo.proto",
}
